# -*- coding: utf-8 -*-
"""ML1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11bJdlW_yngLXih_EvMnc-gKYryU1zuAc
"""

# Find-S Algorithm

def find_s(training_data):
    # Initialize hypothesis with first positive example
    hypothesis = None

    for instance in training_data:
        attributes, label = instance[:-1], instance[-1]

        if label == "Yes":
            if hypothesis is None:
                hypothesis = attributes.copy()
            else:
                for i in range(len(hypothesis)):
                    if hypothesis[i] != attributes[i]:
                        hypothesis[i] = "?"

    return hypothesis


# Dataset
data = [
    ["High", "Good", "Yes", "Good", "Yes"],
    ["High", "Good", "Yes", "Average", "Yes"],
    ["Medium", "Good", "Yes", "Good", "Yes"],
    ["Low", "Average", "No", "Poor", "No"],
    ["Medium", "Average", "No", "Average", "No"],
    ["High", "Poor", "Yes", "Good", "No"]
]

hypothesis_find_s = find_s(data)
print("Final hypothesis by Find-S:", hypothesis_find_s)

# Candidate Elimination Algorithm

def candidate_elimination(data):
    num_attributes = len(data[0]) - 1

    S = ["Ø"] * num_attributes
    G = [["?"] * num_attributes]

    for instance in data:
        attributes, label = instance[:-1], instance[-1]

        if label == "Yes":
            # Update S
            for i in range(num_attributes):
                if S[i] == "Ø":
                    S[i] = attributes[i]
                elif S[i] != attributes[i]:
                    S[i] = "?"

            # Remove inconsistent hypotheses from G
            G = [g for g in G if all(g[i] == "?" or g[i] == attributes[i] for i in range(num_attributes))]

        else:  # Negative example
            new_G = []
            for g in G:
                for i in range(num_attributes):
                    if g[i] == "?" and S[i] != attributes[i]:
                        new_hypothesis = g.copy()
                        new_hypothesis[i] = S[i]
                        new_G.append(new_hypothesis)
            G = new_G

    return S, G


S_final, G_final = candidate_elimination(data)

print("Specific Boundary (S):", S_final)
print("General Boundary (G):", G_final)

# Comparing Find-S and Candidate Elimination Results

find_s_hypothesis = ['?', 'Good', 'Yes', '?']
candidate_S = ['?', 'Good', 'Yes', '?']
candidate_G = [['?', 'Good', 'Yes', '?']]

print("Find-S Hypothesis       :", find_s_hypothesis)
print("Candidate Elimination S :", candidate_S)
print("Candidate Elimination G :", candidate_G)

if find_s_hypothesis == candidate_S:
    print("Both algorithms generated the same hypothesis.")
else:
    print("The hypotheses generated are different.")

# Find-S with noisy data

noisy_data = [
    ["High", "Good", "Yes", "Good", "Yes"],
    ["High", "Good", "Yes", "Average", "Yes"],
    ["Medium", "Good", "Yes", "Good", "Yes"],
    ["High", "Good", "Yes", "Good", "No"]  # Noisy example
]

result_noisy_find_s = find_s(noisy_data)
print("Find-S hypothesis with noisy data:", result_noisy_find_s)

# Candidate Elimination with noisy data

S_noisy, G_noisy = candidate_elimination(noisy_data)

print("Specific Boundary (S) with noise:", S_noisy)
print("General Boundary (G) with noise:", G_noisy)